# Generated by Django 3.1.1 on 2020-11-09 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='covidsafetylevel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='finder.covidsafetylevel'),
        ),
    ]
