# Generated by Django 3.1.1 on 2020-11-09 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_auto_20201109_2324'),
        ('finder', '0002_auto_20201109_2239'),
    ]

    operations = [
    ]
