# Generated by Django 3.1.3 on 2020-11-18 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_merge_20201111_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='covidsafetylevel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finder.covidsafetylevel'),
        ),
        migrations.AlterField(
            model_name='event',
            name='distanced',
            field=models.BooleanField(default=False, help_text='Only required if event not remote'),
        ),
        migrations.AlterField(
            model_name='event',
            name='masks',
            field=models.BooleanField(default=False, help_text='Only required if event not remote'),
        ),
        migrations.AlterField(
            model_name='event',
            name='outdoor',
            field=models.BooleanField(default=False, help_text='Only required if event not remote'),
        ),
        migrations.AlterField(
            model_name='event',
            name='remote',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('guests', models.IntegerField(default=1)),
                ('confirmationno', models.CharField(default='1ABCDEFGH', max_length=50)),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finder.event')),
            ],
        ),
    ]
