# Generated by Django 3.1.1 on 2020-11-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_auto_20201110_0038'),
        ('finder', '0003_merge_20201109_2359'),
    ]

    operations = [
    ]
